---
title: "Practice Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(ggplot2)
library(dplyr)
library(readr)
library(tidyverse)
library(kableExtra)
library(plotly)
library(maps)
library(leaflet)
library(sf)
```

```{r}
# Prepared Data from Education_Comp_Use file

Edu_Comp_22 <- read_csv("Data/Edu_Comp_22.csv", show_col_types = FALSE)
Code_book <- read_csv("Data/Code Book.csv", show_col_types = FALSE)

data <- read.csv("Data/Edu_Comp_22.csv", header = FALSE, skip = 2) # Skip first two rows

col_names <- read.csv("Data/Edu_Comp_22.csv", header = FALSE, nrows = 1) # Read only the first row as column names
colnames(data) <- col_names # Assigns row 1 header to data

cols_to_remove <- grep("M$", col_names) 
data <- data[, -cols_to_remove, drop = FALSE]

new_col_names <- Code_book[[3]] # Extract the third column

colnames(data) <- new_col_names

data <- data[, -ncol(data), drop = FALSE]

data <- data %>% # Putting states in economic regions
  mutate(
    Region = case_when(
      State %in% c("Connecticut", "Maine", "Massachusetts", "New Hampshire", "Rhode Island", "Vermont") ~ "New England",
      State %in% c("Delaware", "District of Columbia", "Maryland", "New Jersey", "New York", "Pennsylvania") ~ "Mideast",
      State %in% c("Illinois", "Indiana", "Michigan", "Ohio", "Wisconsin") ~ "Great Lakes",
      State %in% c("Iowa", "Kansas", "Minnesota", "Missouri", "Nebraska", "North Dakota", "South Dakota") ~ "Plains",
      State %in% c("Alabama", "Arkansas", "Florida", "Georgia", "Kentucky", "Louisiana", "Mississippi", "North Carolina", "South Carolina", "Tennessee", "Virginia", "West Virginia") ~ "Southeast",
      State %in% c("Arizona", "New Mexico", "Oklahoma", "Texas") ~ "Southwest",
      State %in% c("Colorado", "Idaho", "Montana", "Utah", "Wyoming") ~ "Rocky Mountain",
      State %in% c("Puerto Rico") ~ "Puerto Rico",
      State %in% c("Alaska", "California", "Hawaii", "Nevada", "Oregon", "Washington") ~ "Far West",
      TRUE ~ NA_character_
    )
  )

data <- data %>% 
  mutate(
    Prop_no_Comp = (`< HS no Comp`+ `< HS w/Comp w/out IS`+ `HS no Comp`+ `HS some Col w/Comp w/out IS`+ `BA+  no Comp` + `BA+  w/Comp w/out IS`)/`State Total`
  )

# New columns for proportion of people with no internet access or no computer by education level, that is a conditional probability, P(no_Comp|education level)
data <- data %>%
  mutate(
    lths_Prop_no_Comp = ((`< HS no Comp`+ `< HS w/Comp w/out IS`)/`< HS Total`), 
    hs_Prop_no_Comp = ((`HS no Comp`+ `HS some Col w/Comp w/out IS`)/`HS some Col Total`),
    ba_Prop_no_Comp = ((`BA+  no Comp` + `BA+  w/Comp w/out IS`)/`BA+ Total`))

summary_data <- data %>%
  group_by(Region) %>%
  summarise(
    mean_no_Comp = mean(Prop_no_Comp),
    median_no_Comp = median(Prop_no_Comp)
  )

# Prepare data for Boxplot No Computer or Internet Access by Education level
edu_level_data <- data %>%
  select(Prop_no_Comp, lths_Prop_no_Comp, hs_Prop_no_Comp, ba_Prop_no_Comp
  )
# Rename columns to more understandable
colnames(edu_level_data) <- c("USA", "Less Than High School", "HS and Some College", "Bachelors Plus")

Summary_Edu_level <- summary(edu_level_data) %>%
  kable("html") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))

# Long format for plotting
edu_level_data_long <- tidyr::gather(edu_level_data, key = "Variable", value = "Proportion") #convert wide to long

# Reorder the levels of education for x axis
edu_level_data_long$Variable <- factor(edu_level_data_long$Variable, 
                                       levels = c("Less Than High School", "HS and Some College", "Bachelors Plus", "USA"))

# 1 Categorical Plot
#ascending order
summary_data <- summary_data %>% arrange(mean_no_Comp)
Econ <- ggplot(summary_data, aes(x = reorder(Region, mean_no_Comp), y = mean_no_Comp)) +
  geom_bar(stat = "identity", fill = "darkblue") +
  labs(x = "Bureau of Economic Analysis Regions", y = "Proportion") +
  ggtitle("USA: No Computer or Internet Access in 2022") + 
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
Econ

# 2 Numerical Plot
box_Edu_Level <- ggplot(edu_level_data_long, aes(x = Variable, y = Proportion, fill = Variable)) +
  geom_boxplot(position = position_dodge(width = 0.75), width = 0.5, alpha = 0.5) +
  labs(title = 'USA: No Computer or Internet Subscription by Education Level',
       x = '',
       y = 'Proportion',
       fill = 'Education Level') +
  scale_fill_manual(values = c( "skyblue", "navy", "white", "red")) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  guides(fill = FALSE) # Remove legend
box_Edu_Level

# 3 For Bivariate Cat-Cat Plot 
#Education Level and No Computer in Internet Subscription

# Prepare data, pivot long
data_long_edu_level <- pivot_longer(data, cols = c("lths_Prop_no_Comp", "hs_Prop_no_Comp", "ba_Prop_no_Comp"), names_to = "Education_Level", values_to = "Percent")

education_labels <- c("Bachelor's or Higher", "High School and Some College", "Less Than High School")

data_long_edu_level$Education_Level <- factor(data_long_edu_level$Education_Level, levels = c("ba_Prop_no_Comp", "hs_Prop_no_Comp", "lths_Prop_no_Comp"), labels = education_labels)

data_long_edu_level <- data_long_edu_level %>% arrange(Region)

# Plot 
c_c <- ggplot(data_long_edu_level, aes(x = reorder(Region, Prop_no_Comp), y = Percent, fill = Education_Level)) + 
  geom_bar(position = "fill", stat = "identity") +
  labs(title = "No Computer or Internet by Economic Region and Education Level", x = "", y = "Percent")+
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
c_c
#chart D map
rm(list = ls())
##
usaMap=read_sf("C:/Users/shres/Documents/GitHub/Data-Visualization/Data/gz_2010_us_040_00_500k.json")

ggplot(data = usaMap)+ geom_sf() +coord_sf(crs = st_crs(2163)) 
variables=read.csv("Data/data_for_map.csv")
head(variables)
head(usaMap)
sort(usaMap$NAME)==sort(variables$State)
usaMap=merge(usaMap,variables, by.x='NAME', by.y='State')
usaMap

usaMap %>%
  group_by(Region) %>%
  summarise_at(vars(Prop_no_Comp), list(Prop_no_Comp_mean=mean)) ->variablesByRegion

#newMap
variablesByRegion
ggplot(variablesByRegion) + geom_sf(aes(fill=Prop_no_Comp_mean)) +coord_sf(crs = st_crs(2163)) 


```

#Column {data-width=500}
-----------------------------------------------------------------------

### Chart A

```{r}
ggplotly(Econ)
```

<<<<<<< HEAD
Column {data-width=550}
-----------------------------------------------------------------------
=======

>>>>>>> 665036530569ad6f682629bcc5813990a195a5a5

### Chart B

```{r}
ggplotly(box_Edu_Level)
```
Column {data-width=350}
-----------------------------------------------------------------------
### Chart C

```{r}
ggplotly(c_c)

```

### Chart D

```{r}
```


