---
title: "690V Data Visualization Practice"
author: "Group 2"
date: "`r Sys.Date()`"
format:
  html:
    toc: true
    code-fold: true
    code-copy: true
    code-tools: true
---

```{r}
install.packages("reader")
```

```{r setup, include=FALSE}
library(readr)
library(tidyverse)
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```

## Import Data

```{r setup, include=FALSE}
Edu_Comp_22_orig_2headers <- read_csv("Data/Edu_Comp_22.csv")
# Remove second header
Edu_Comp_22_orig <- Edu_Comp_22_orig_2headers[-2, ] 

```

## Prepare Data

```{r}
# Remove magrin of error columns
Edu_Comp_22_remove_moe <- function(Edu_Comp_22_orig) {
  cols_to_remove <- grep("M$", names(Edu_Comp_22_orig))
  Edu_Comp_22 <- Edu_Comp_22_orig[, -cols_to_remove, drop = FALSE]
  return(Edu_Comp_22)
}

Edu_Comp_22 <- Edu_Comp_22_remove_moe(Edu_Comp_22_orig)

```

```{r}
# Remove the second header
colnames(Edu_Comp_22) <- as.character(Edu_Comp_22[2, ])
Edu_Comp_22 <- Edu_Comp_22[-2, ]

# Print the resulting data frame
print(Edu_Comp_22)

```

```{r}

```


## Sample Histogram

### fyi, renamed data to Edu_Comp_22

```{r}
ggplot(Edu_Comp_22, aes(x = B28006_001E)) +
  geom_histogram(binwidth = 1000000, fill = "skyblue", color = "black") +
  labs(title = "State Population Distribution",
       x = "Population in Millions",
       y = "Number of States") +
  scale_y_continuous(breaks = seq(0, 14, by = 2),
                     labels = function(x) format(x, scientific = FALSE)) +
  scale_x_continuous(breaks = seq(0, max(Edu_Comp_22$B28006_001E), by = 5e6),
                     labels = function(x) format(x / 1e6, scientific = FALSE, big.mark = ",")) +
  theme_minimal()

```


```{r}
ggplot(data, aes(x = B28006_019E)) +
  geom_histogram(bins = 50, fill = 'red', color = 'black') +
  labs(title = 'Internet access distribution',
      x = 'internet access',
      y = 'frequency') +
      facet_wrap(~NAME)
```